### ISSUE TITLE
Starter project test

### ISSUE THREAD

**Issue by AiRuiChen** [AiRuiChen/dowel#1]
@avnishn @zequnyu

Hi,

I noticed that we are required to deliver our code with tests. However, the desired functionality will change the expected output of [test_record_inconsistent()](https://github.com/AiRuiChen/dowel/blob/master/tests/dowel/test_csv_output.py#L38). The newly added key "bar" should also be recorded. (Please correct me if I am wrong)

Should I add my unit test in test_csv_output.py and change affected tests as well? Or should I create a new test file just for this updated functionality only?

**Comment by AiRuiChen** [comment]
Another question: when CsvOutput encounters a new key, should it still emits a warning? I think changing this will also affect the old tests.

**Comment by avnishn** [comment]
This is a great question!

You should remove or ammend the test as necessary. I think it should be removed, but make sure that any other functionality besides inconsistent keys is preserved.

**Comment by AiRuiChen** [comment]
> This is a great question!
> 
> You should remove or ammend the test as necessary. I think it should be removed, but make sure that any other functionality besides inconsistent keys is preserved.

Got it, Thank you!

Sorry I accidentally deleted your reply;(
